set(_CATKIN_CURRENT_PACKAGE "mr_bringup")
set(mr_bringup_VERSION "0.1.0")
set(mr_bringup_MAINTAINER "lmn <lmn@todo.todo>")
set(mr_bringup_PACKAGE_FORMAT "1")
set(mr_bringup_BUILD_DEPENDS )
set(mr_bringup_BUILD_EXPORT_DEPENDS "tf2_ros" "mr_description" "mra7b_description" "mra7b_moveit_config" "mrp2a_description" "mrp2a_moveit_config" "mra7_gazebo" "mr_driver")
set(mr_bringup_BUILDTOOL_DEPENDS "catkin")
set(mr_bringup_BUILDTOOL_EXPORT_DEPENDS )
set(mr_bringup_EXEC_DEPENDS "tf2_ros" "mr_description" "mra7b_description" "mra7b_moveit_config" "mrp2a_description" "mrp2a_moveit_config" "mra7_gazebo" "mr_driver")
set(mr_bringup_RUN_DEPENDS "tf2_ros" "mr_description" "mra7b_description" "mra7b_moveit_config" "mrp2a_description" "mrp2a_moveit_config" "mra7_gazebo" "mr_driver")
set(mr_bringup_TEST_DEPENDS )
set(mr_bringup_DOC_DEPENDS )
set(mr_bringup_URL_WEBSITE "")
set(mr_bringup_URL_BUGTRACKER "")
set(mr_bringup_URL_REPOSITORY "")
set(mr_bringup_DEPRECATED "")