set(_CATKIN_CURRENT_PACKAGE "mr_driver")
set(mr_driver_VERSION "0.1.0")
set(mr_driver_MAINTAINER "Lou Wei <Wei@todo.todo>")
set(mr_driver_PACKAGE_FORMAT "1")
set(mr_driver_BUILD_DEPENDS "roscpp" "hardware_interface" "controller_manager" "actionlib" "control_msgs" "std_msgs" "sensor_msgs" "trajectory_msgs" "tf" "mr_msgs")
set(mr_driver_BUILD_EXPORT_DEPENDS "roscpp" "hardware_interface" "controller_manager" "ros_controllers" "actionlib" "control_msgs" "sensor_msgs" "std_msgs" "trajectory_msgs" "tf" "mr_msgs")
set(mr_driver_BUILDTOOL_DEPENDS "catkin")
set(mr_driver_BUILDTOOL_EXPORT_DEPENDS )
set(mr_driver_EXEC_DEPENDS "roscpp" "hardware_interface" "controller_manager" "ros_controllers" "actionlib" "control_msgs" "sensor_msgs" "std_msgs" "trajectory_msgs" "tf" "mr_msgs")
set(mr_driver_RUN_DEPENDS "roscpp" "hardware_interface" "controller_manager" "ros_controllers" "actionlib" "control_msgs" "sensor_msgs" "std_msgs" "trajectory_msgs" "tf" "mr_msgs")
set(mr_driver_TEST_DEPENDS )
set(mr_driver_DOC_DEPENDS )
set(mr_driver_URL_WEBSITE "")
set(mr_driver_URL_BUGTRACKER "")
set(mr_driver_URL_REPOSITORY "")
set(mr_driver_DEPRECATED "")