set(_CATKIN_CURRENT_PACKAGE "mr_gazebo")
set(mr_gazebo_VERSION "1.2.0")
set(mr_gazebo_MAINTAINER "Felix Messmer <fxm@ipa.fhg.de>, G.A. vd. Hoorn <g.a.vanderhoorn@tudelft.nl>")
set(mr_gazebo_PACKAGE_FORMAT "1")
set(mr_gazebo_BUILD_DEPENDS )
set(mr_gazebo_BUILD_EXPORT_DEPENDS "mr_description" "gazebo_ros" "gazebo_ros_control" "joint_state_controller" "joint_trajectory_controller" "effort_controllers" "robot_state_publisher" "controller_manager")
set(mr_gazebo_BUILDTOOL_DEPENDS "catkin")
set(mr_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(mr_gazebo_EXEC_DEPENDS "mr_description" "gazebo_ros" "gazebo_ros_control" "joint_state_controller" "joint_trajectory_controller" "effort_controllers" "robot_state_publisher" "controller_manager")
set(mr_gazebo_RUN_DEPENDS "mr_description" "gazebo_ros" "gazebo_ros_control" "joint_state_controller" "joint_trajectory_controller" "effort_controllers" "robot_state_publisher" "controller_manager")
set(mr_gazebo_TEST_DEPENDS )
set(mr_gazebo_DOC_DEPENDS )
set(mr_gazebo_URL_WEBSITE "http://ros.org/wiki/ur_gazebo")
set(mr_gazebo_URL_BUGTRACKER "")
set(mr_gazebo_URL_REPOSITORY "")
set(mr_gazebo_DEPRECATED "")